package dgroomes.springplayground.caching;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;

import java.util.Random;

/**
 * Toy example with a {@link Cacheable} method
 */
@Service
public class FortuneService {

    private static final Logger log = LoggerFactory.getLogger(FortuneService.class);

    private final Random random = new Random();

    /**
     * Get a fortune.
     * <p>
     * This method prints the current stack trace to illustrate that it is referenced from a proxied class generated by
     * Spring.
     */
    @Cacheable(value = "fortune")
    public String getFortune(String name) {
        log.trace("getFortune stacktrace:\n{}", Util.formatStackTrace(Thread.currentThread().getStackTrace()));
        var luckyNumber = random.nextInt(11);
        return String.format("%s, your lucky number is %s", name, luckyNumber);
    }
}
