spring:
  cache:
    type: simple
logging:
  level:
    org.springframework.cache: trace
    dgroomes.springplayground.caching: trace
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,caches
