spring:
  cache:
    type: caffeine
    cache-names:
      - fortune
logging:
  level:
    org.springframework.cache: trace
    dgroomes.springplayground.caching: trace
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,caches
