name: Assemble all sub-projects

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  assemble-all-sub-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Assemble all sub-projects
        run: ./gradlew assembleAll
